add: task 2
js-tasks-ru/js-20210615_aleksandr46 pull request #2
Opened 2021-06-22 16:48 UTC by kvalexandr

2021-06-22 16:49 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-06-24 10:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2021-06-24 19:24 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    const arrPath = path.split(".");
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2021-06-24 19:24 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    for (let i = 0; i < arrPath.length; i++) {
а здесь точно нужен цикл `for`, может лучше `for...of`?

2021-06-24 19:24 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
>  export function invertObj(obj) {
good 👍

2021-06-24 19:25 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +  return;
здесь нет необходимости писать `return` функция по умолчанию возвращает `undefined`

2021-06-24 19:25 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  return arr
более короткий способ копировать массив: `[...arr]`

2021-06-24 19:26 UTC, dosandk requested changes
createGetter решение необходимо поправить

2021-06-25 10:50 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-06-25 16:27 UTC, dosandk approved these changes
good 👍

2021-06-25 16:28 UTC, merged